# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\NUCER\Google Drive\HiWi\Science_Project\Science_Project.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 566)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/research4-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAcceptDrops(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.display_tab = QtWidgets.QWidget()
        self.display_tab.setObjectName("display_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.display_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(109, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem2)
        self.fifth_data_not_available_label = QtWidgets.QLabel(self.display_tab)
        self.fifth_data_not_available_label.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(True)
        self.fifth_data_not_available_label.setFont(font)
        self.fifth_data_not_available_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.fifth_data_not_available_label.setObjectName("fifth_data_not_available_label")
        self.verticalLayout_2.addWidget(self.fifth_data_not_available_label)
        self.fifth_pushButton = QtWidgets.QPushButton(self.display_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fifth_pushButton.sizePolicy().hasHeightForWidth())
        self.fifth_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fifth_pushButton.setFont(font)
        self.fifth_pushButton.setStyleSheet("QPushButton {background-color: #ffa500; border: 1px solid white;border-radius: 10px; } QPushButton:checked{ background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(255, 165, 0, 255), stop:1 rgba(252, 194, 88, 255)); border: 5px solid #ffa500;border-radius: 30px;}")
        self.fifth_pushButton.setCheckable(True)
        self.fifth_pushButton.setObjectName("fifth_pushButton")
        self.verticalLayout_2.addWidget(self.fifth_pushButton)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_41 = QtWidgets.QLabel(self.display_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.fifth_current_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.fifth_current_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fifth_current_lineEdit.sizePolicy().hasHeightForWidth())
        self.fifth_current_lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fifth_current_lineEdit.setFont(font)
        self.fifth_current_lineEdit.setObjectName("fifth_current_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fifth_current_lineEdit)
        self.label_45 = QtWidgets.QLabel(self.display_tab)
        self.label_45.setObjectName("label_45")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.fifth_a_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.fifth_a_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fifth_a_lineEdit.sizePolicy().hasHeightForWidth())
        self.fifth_a_lineEdit.setSizePolicy(sizePolicy)
        self.fifth_a_lineEdit.setObjectName("fifth_a_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fifth_a_lineEdit)
        self.label_46 = QtWidgets.QLabel(self.display_tab)
        self.label_46.setObjectName("label_46")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.fifth_b_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.fifth_b_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fifth_b_lineEdit.sizePolicy().hasHeightForWidth())
        self.fifth_b_lineEdit.setSizePolicy(sizePolicy)
        self.fifth_b_lineEdit.setObjectName("fifth_b_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fifth_b_lineEdit)
        self.label_47 = QtWidgets.QLabel(self.display_tab)
        self.label_47.setObjectName("label_47")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.fifth_c_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.fifth_c_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fifth_c_lineEdit.sizePolicy().hasHeightForWidth())
        self.fifth_c_lineEdit.setSizePolicy(sizePolicy)
        self.fifth_c_lineEdit.setObjectName("fifth_c_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fifth_c_lineEdit)
        self.label_48 = QtWidgets.QLabel(self.display_tab)
        self.label_48.setObjectName("label_48")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.fifth_d_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.fifth_d_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fifth_d_lineEdit.sizePolicy().hasHeightForWidth())
        self.fifth_d_lineEdit.setSizePolicy(sizePolicy)
        self.fifth_d_lineEdit.setObjectName("fifth_d_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fifth_d_lineEdit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 2, 5, 1, 1)
        self.first_verticalLayout = QtWidgets.QVBoxLayout()
        self.first_verticalLayout.setObjectName("first_verticalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.first_verticalLayout.addItem(spacerItem3)
        self.first_data_not_available_label = QtWidgets.QLabel(self.display_tab)
        self.first_data_not_available_label.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(True)
        self.first_data_not_available_label.setFont(font)
        self.first_data_not_available_label.setAutoFillBackground(False)
        self.first_data_not_available_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.first_data_not_available_label.setObjectName("first_data_not_available_label")
        self.first_verticalLayout.addWidget(self.first_data_not_available_label)
        self.first_pushButton = QtWidgets.QPushButton(self.display_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.first_pushButton.sizePolicy().hasHeightForWidth())
        self.first_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.first_pushButton.setFont(font)
        self.first_pushButton.setStyleSheet("QPushButton {background-color:#07a2ef; border: 1px solid white;border-radius: 10px; } QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(7, 162, 239, 255), stop:1 rgba(111, 198, 242)); border: 5px solid #07a2ef;border-radius: 30px;}")
        self.first_pushButton.setCheckable(True)
        self.first_pushButton.setObjectName("first_pushButton")
        self.first_verticalLayout.addWidget(self.first_pushButton)
        self.first_formLayout = QtWidgets.QFormLayout()
        self.first_formLayout.setObjectName("first_formLayout")
        self.label_3 = QtWidgets.QLabel(self.display_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.first_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.first_current_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.first_current_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.first_current_lineEdit.sizePolicy().hasHeightForWidth())
        self.first_current_lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.first_current_lineEdit.setFont(font)
        self.first_current_lineEdit.setObjectName("first_current_lineEdit")
        self.first_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.first_current_lineEdit)
        self.label_7 = QtWidgets.QLabel(self.display_tab)
        self.label_7.setObjectName("label_7")
        self.first_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.first_a_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.first_a_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.first_a_lineEdit.sizePolicy().hasHeightForWidth())
        self.first_a_lineEdit.setSizePolicy(sizePolicy)
        self.first_a_lineEdit.setObjectName("first_a_lineEdit")
        self.first_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.first_a_lineEdit)
        self.label_8 = QtWidgets.QLabel(self.display_tab)
        self.label_8.setObjectName("label_8")
        self.first_formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.first_b_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.first_b_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.first_b_lineEdit.sizePolicy().hasHeightForWidth())
        self.first_b_lineEdit.setSizePolicy(sizePolicy)
        self.first_b_lineEdit.setObjectName("first_b_lineEdit")
        self.first_formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.first_b_lineEdit)
        self.label_9 = QtWidgets.QLabel(self.display_tab)
        self.label_9.setObjectName("label_9")
        self.first_formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.first_c_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.first_c_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.first_c_lineEdit.sizePolicy().hasHeightForWidth())
        self.first_c_lineEdit.setSizePolicy(sizePolicy)
        self.first_c_lineEdit.setObjectName("first_c_lineEdit")
        self.first_formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.first_c_lineEdit)
        self.label_10 = QtWidgets.QLabel(self.display_tab)
        self.label_10.setObjectName("label_10")
        self.first_formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.first_d_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.first_d_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.first_d_lineEdit.sizePolicy().hasHeightForWidth())
        self.first_d_lineEdit.setSizePolicy(sizePolicy)
        self.first_d_lineEdit.setObjectName("first_d_lineEdit")
        self.first_formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.first_d_lineEdit)
        self.first_verticalLayout.addLayout(self.first_formLayout)
        self.gridLayout_2.addLayout(self.first_verticalLayout, 0, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_6.addItem(spacerItem4)
        self.second_data_not_available_label = QtWidgets.QLabel(self.display_tab)
        self.second_data_not_available_label.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(True)
        self.second_data_not_available_label.setFont(font)
        self.second_data_not_available_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.second_data_not_available_label.setObjectName("second_data_not_available_label")
        self.verticalLayout_6.addWidget(self.second_data_not_available_label)
        self.second_pushButton = QtWidgets.QPushButton(self.display_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.second_pushButton.sizePolicy().hasHeightForWidth())
        self.second_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.second_pushButton.setFont(font)
        self.second_pushButton.setStyleSheet("QPushButton {background-color: #f44253; border: 1px solid white;border-radius: 10px; } QPushButton:checked{ background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(244, 66, 83, 255), stop:1 rgba(247, 111, 124, 255)); border: 5px solid #f44253;border-radius: 30px;}")
        self.second_pushButton.setCheckable(True)
        self.second_pushButton.setObjectName("second_pushButton")
        self.verticalLayout_6.addWidget(self.second_pushButton)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_13 = QtWidgets.QLabel(self.display_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.second_current_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.second_current_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.second_current_lineEdit.sizePolicy().hasHeightForWidth())
        self.second_current_lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.second_current_lineEdit.setFont(font)
        self.second_current_lineEdit.setObjectName("second_current_lineEdit")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.second_current_lineEdit)
        self.label_17 = QtWidgets.QLabel(self.display_tab)
        self.label_17.setObjectName("label_17")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.second_a_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.second_a_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.second_a_lineEdit.sizePolicy().hasHeightForWidth())
        self.second_a_lineEdit.setSizePolicy(sizePolicy)
        self.second_a_lineEdit.setObjectName("second_a_lineEdit")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.second_a_lineEdit)
        self.label_18 = QtWidgets.QLabel(self.display_tab)
        self.label_18.setObjectName("label_18")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.second_b_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.second_b_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.second_b_lineEdit.sizePolicy().hasHeightForWidth())
        self.second_b_lineEdit.setSizePolicy(sizePolicy)
        self.second_b_lineEdit.setObjectName("second_b_lineEdit")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.second_b_lineEdit)
        self.label_19 = QtWidgets.QLabel(self.display_tab)
        self.label_19.setObjectName("label_19")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.second_c_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.second_c_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.second_c_lineEdit.sizePolicy().hasHeightForWidth())
        self.second_c_lineEdit.setSizePolicy(sizePolicy)
        self.second_c_lineEdit.setObjectName("second_c_lineEdit")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.second_c_lineEdit)
        self.label_20 = QtWidgets.QLabel(self.display_tab)
        self.label_20.setObjectName("label_20")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.second_d_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.second_d_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.second_d_lineEdit.sizePolicy().hasHeightForWidth())
        self.second_d_lineEdit.setSizePolicy(sizePolicy)
        self.second_d_lineEdit.setObjectName("second_d_lineEdit")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.second_d_lineEdit)
        self.verticalLayout_6.addLayout(self.formLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 3, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_4.addItem(spacerItem5)
        self.third_data_not_available_label = QtWidgets.QLabel(self.display_tab)
        self.third_data_not_available_label.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(True)
        self.third_data_not_available_label.setFont(font)
        self.third_data_not_available_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.third_data_not_available_label.setObjectName("third_data_not_available_label")
        self.verticalLayout_4.addWidget(self.third_data_not_available_label)
        self.third_pushButton = QtWidgets.QPushButton(self.display_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.third_pushButton.sizePolicy().hasHeightForWidth())
        self.third_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.third_pushButton.setFont(font)
        self.third_pushButton.setStyleSheet("QPushButton {background-color: #00d157; border: 1px solid white;border-radius: 10px; } QPushButton:checked{ background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(0, 209, 87, 255), stop:1 rgba(110, 239, 164, 255)); border: 5px solid #00d157;border-radius: 30px;}")
        self.third_pushButton.setCheckable(True)
        self.third_pushButton.setObjectName("third_pushButton")
        self.verticalLayout_4.addWidget(self.third_pushButton)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_23 = QtWidgets.QLabel(self.display_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.third_current_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.third_current_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.third_current_lineEdit.sizePolicy().hasHeightForWidth())
        self.third_current_lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.third_current_lineEdit.setFont(font)
        self.third_current_lineEdit.setObjectName("third_current_lineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.third_current_lineEdit)
        self.label_27 = QtWidgets.QLabel(self.display_tab)
        self.label_27.setObjectName("label_27")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.third_a_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.third_a_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.third_a_lineEdit.sizePolicy().hasHeightForWidth())
        self.third_a_lineEdit.setSizePolicy(sizePolicy)
        self.third_a_lineEdit.setObjectName("third_a_lineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.third_a_lineEdit)
        self.label_28 = QtWidgets.QLabel(self.display_tab)
        self.label_28.setObjectName("label_28")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.third_b_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.third_b_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.third_b_lineEdit.sizePolicy().hasHeightForWidth())
        self.third_b_lineEdit.setSizePolicy(sizePolicy)
        self.third_b_lineEdit.setObjectName("third_b_lineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.third_b_lineEdit)
        self.label_29 = QtWidgets.QLabel(self.display_tab)
        self.label_29.setObjectName("label_29")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.third_c_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.third_c_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.third_c_lineEdit.sizePolicy().hasHeightForWidth())
        self.third_c_lineEdit.setSizePolicy(sizePolicy)
        self.third_c_lineEdit.setObjectName("third_c_lineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.third_c_lineEdit)
        self.label_30 = QtWidgets.QLabel(self.display_tab)
        self.label_30.setObjectName("label_30")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.third_d_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.third_d_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.third_d_lineEdit.sizePolicy().hasHeightForWidth())
        self.third_d_lineEdit.setSizePolicy(sizePolicy)
        self.third_d_lineEdit.setObjectName("third_d_lineEdit")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.third_d_lineEdit)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 2, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem8)
        self.fourth_data_not_available_label = QtWidgets.QLabel(self.display_tab)
        self.fourth_data_not_available_label.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(True)
        self.fourth_data_not_available_label.setFont(font)
        self.fourth_data_not_available_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.fourth_data_not_available_label.setObjectName("fourth_data_not_available_label")
        self.verticalLayout_3.addWidget(self.fourth_data_not_available_label)
        self.fourth_pushButton = QtWidgets.QPushButton(self.display_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fourth_pushButton.sizePolicy().hasHeightForWidth())
        self.fourth_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fourth_pushButton.setFont(font)
        self.fourth_pushButton.setStyleSheet("QPushButton {background-color: #e9f416; border: 1px solid white;border-radius: 10px;}QPushButton:checked{ background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,   stop:0 rgba(233, 244, 22, 255), stop:1 rgba(244, 252, 100, 255)); border: 5px solid #e9f416;border-radius: 30px;}")
        self.fourth_pushButton.setCheckable(True)
        self.fourth_pushButton.setObjectName("fourth_pushButton")
        self.verticalLayout_3.addWidget(self.fourth_pushButton)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_32 = QtWidgets.QLabel(self.display_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.fourth_current_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.fourth_current_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fourth_current_lineEdit.sizePolicy().hasHeightForWidth())
        self.fourth_current_lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fourth_current_lineEdit.setFont(font)
        self.fourth_current_lineEdit.setObjectName("fourth_current_lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fourth_current_lineEdit)
        self.label_36 = QtWidgets.QLabel(self.display_tab)
        self.label_36.setObjectName("label_36")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.fourth_a_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.fourth_a_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fourth_a_lineEdit.sizePolicy().hasHeightForWidth())
        self.fourth_a_lineEdit.setSizePolicy(sizePolicy)
        self.fourth_a_lineEdit.setObjectName("fourth_a_lineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fourth_a_lineEdit)
        self.label_37 = QtWidgets.QLabel(self.display_tab)
        self.label_37.setObjectName("label_37")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.fourth_b_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.fourth_b_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fourth_b_lineEdit.sizePolicy().hasHeightForWidth())
        self.fourth_b_lineEdit.setSizePolicy(sizePolicy)
        self.fourth_b_lineEdit.setObjectName("fourth_b_lineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fourth_b_lineEdit)
        self.label_38 = QtWidgets.QLabel(self.display_tab)
        self.label_38.setObjectName("label_38")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.fourth_c_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.fourth_c_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fourth_c_lineEdit.sizePolicy().hasHeightForWidth())
        self.fourth_c_lineEdit.setSizePolicy(sizePolicy)
        self.fourth_c_lineEdit.setObjectName("fourth_c_lineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fourth_c_lineEdit)
        self.label_39 = QtWidgets.QLabel(self.display_tab)
        self.label_39.setObjectName("label_39")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.fourth_d_lineEdit = QtWidgets.QLineEdit(self.display_tab)
        self.fourth_d_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fourth_d_lineEdit.sizePolicy().hasHeightForWidth())
        self.fourth_d_lineEdit.setSizePolicy(sizePolicy)
        self.fourth_d_lineEdit.setObjectName("fourth_d_lineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fourth_d_lineEdit)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 2, 1, 1, 1)
        self.tabWidget.addTab(self.display_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.settings_tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.baudrateLabel = QtWidgets.QLabel(self.groupBox)
        self.baudrateLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.baudrateLabel.setObjectName("baudrateLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.baudrateLabel)
        self.baudrateComboBox = QtWidgets.QComboBox(self.groupBox)
        self.baudrateComboBox.setMaxVisibleItems(20)
        self.baudrateComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.baudrateComboBox.setObjectName("baudrateComboBox")
        self.baudrateComboBox.addItem("")
        self.baudrateComboBox.addItem("")
        self.baudrateComboBox.addItem("")
        self.baudrateComboBox.addItem("")
        self.baudrateComboBox.addItem("")
        self.baudrateComboBox.addItem("")
        self.baudrateComboBox.addItem("")
        self.baudrateComboBox.addItem("")
        self.baudrateComboBox.addItem("")
        self.baudrateComboBox.addItem("")
        self.baudrateComboBox.addItem("")
        self.baudrateComboBox.addItem("")
        self.baudrateComboBox.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.baudrateComboBox)
        self.portLabel = QtWidgets.QLabel(self.groupBox)
        self.portLabel.setObjectName("portLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.portLabel)
        self.portlineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.portlineEdit.setClearButtonEnabled(True)
        self.portlineEdit.setObjectName("portlineEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.portlineEdit)
        self.gridLayout_4.addLayout(self.formLayout_4, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.read_pushButton = QtWidgets.QPushButton(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_pushButton.sizePolicy().hasHeightForWidth())
        self.read_pushButton.setSizePolicy(sizePolicy)
        self.read_pushButton.setStyleSheet("")
        self.read_pushButton.setCheckable(True)
        self.read_pushButton.setObjectName("read_pushButton")
        self.horizontalLayout_2.addWidget(self.read_pushButton)
        self.stop_pushButton = QtWidgets.QPushButton(self.settings_tab)
        self.stop_pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_pushButton.sizePolicy().hasHeightForWidth())
        self.stop_pushButton.setSizePolicy(sizePolicy)
        self.stop_pushButton.setStyleSheet("")
        self.stop_pushButton.setCheckable(True)
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.horizontalLayout_2.addWidget(self.stop_pushButton)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.ei_logo_label = QtWidgets.QLabel(self.settings_tab)
        self.ei_logo_label.setText("")
        self.ei_logo_label.setPixmap(QtGui.QPixmap("Images/EI_logo_with-icons-300x212.png"))
        self.ei_logo_label.setScaledContents(False)
        self.ei_logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ei_logo_label.setObjectName("ei_logo_label")
        self.verticalLayout_7.addWidget(self.ei_logo_label)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem11)
        self.tabWidget.addTab(self.settings_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Holo.lab"))
        self.fifth_data_not_available_label.setText(_translate("MainWindow", "<< Data not available >>"))
        self.fifth_pushButton.setText(_translate("MainWindow", "5"))
        self.label_41.setText(_translate("MainWindow", "Current"))
        self.fifth_current_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_45.setText(_translate("MainWindow", "A"))
        self.fifth_a_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_46.setText(_translate("MainWindow", "B"))
        self.fifth_b_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_47.setText(_translate("MainWindow", "C"))
        self.fifth_c_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_48.setText(_translate("MainWindow", "D"))
        self.fifth_d_lineEdit.setText(_translate("MainWindow", "0"))
        self.first_data_not_available_label.setText(_translate("MainWindow", "<< Data not available >>"))
        self.first_pushButton.setText(_translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "Current"))
        self.first_current_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "A"))
        self.first_a_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "B"))
        self.first_b_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "C"))
        self.first_c_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "D"))
        self.first_d_lineEdit.setText(_translate("MainWindow", "0"))
        self.second_data_not_available_label.setText(_translate("MainWindow", "<< Data not available >>"))
        self.second_pushButton.setText(_translate("MainWindow", "2"))
        self.label_13.setText(_translate("MainWindow", "Current"))
        self.second_current_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "A"))
        self.second_a_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "B"))
        self.second_b_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "C"))
        self.second_c_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "D"))
        self.second_d_lineEdit.setText(_translate("MainWindow", "0"))
        self.third_data_not_available_label.setText(_translate("MainWindow", "<< Data not available >>"))
        self.third_pushButton.setText(_translate("MainWindow", "3"))
        self.label_23.setText(_translate("MainWindow", "Current"))
        self.third_current_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_27.setText(_translate("MainWindow", "A"))
        self.third_a_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_28.setText(_translate("MainWindow", "B"))
        self.third_b_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_29.setText(_translate("MainWindow", "C"))
        self.third_c_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "D"))
        self.third_d_lineEdit.setText(_translate("MainWindow", "0"))
        self.fourth_data_not_available_label.setText(_translate("MainWindow", "<< Data not available >>"))
        self.fourth_pushButton.setText(_translate("MainWindow", "4"))
        self.label_32.setText(_translate("MainWindow", "Current"))
        self.fourth_current_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_36.setText(_translate("MainWindow", "A"))
        self.fourth_a_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_37.setText(_translate("MainWindow", "B"))
        self.fourth_b_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_38.setText(_translate("MainWindow", "C"))
        self.fourth_c_lineEdit.setText(_translate("MainWindow", "0"))
        self.label_39.setText(_translate("MainWindow", "D"))
        self.fourth_d_lineEdit.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.display_tab), _translate("MainWindow", "Display"))
        self.groupBox.setTitle(_translate("MainWindow", "Serial Port Settings"))
        self.baudrateLabel.setText(_translate("MainWindow", "Baudrate"))
        self.baudrateComboBox.setCurrentText(_translate("MainWindow", "115200"))
        self.baudrateComboBox.setItemText(0, _translate("MainWindow", "115200"))
        self.baudrateComboBox.setItemText(1, _translate("MainWindow", "57600"))
        self.baudrateComboBox.setItemText(2, _translate("MainWindow", "38400"))
        self.baudrateComboBox.setItemText(3, _translate("MainWindow", "28800"))
        self.baudrateComboBox.setItemText(4, _translate("MainWindow", "19200"))
        self.baudrateComboBox.setItemText(5, _translate("MainWindow", "14400"))
        self.baudrateComboBox.setItemText(6, _translate("MainWindow", "9600"))
        self.baudrateComboBox.setItemText(7, _translate("MainWindow", "4800"))
        self.baudrateComboBox.setItemText(8, _translate("MainWindow", "2400"))
        self.baudrateComboBox.setItemText(9, _translate("MainWindow", "1200"))
        self.baudrateComboBox.setItemText(10, _translate("MainWindow", "900"))
        self.baudrateComboBox.setItemText(11, _translate("MainWindow", "600"))
        self.baudrateComboBox.setItemText(12, _translate("MainWindow", "300"))
        self.portLabel.setText(_translate("MainWindow", "Port"))
        self.portlineEdit.setText(_translate("MainWindow", "COM3"))
        self.read_pushButton.setText(_translate("MainWindow", "Read"))
        self.stop_pushButton.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), _translate("MainWindow", "Settings"))

